### PR TITLE
Stuff i forgot xd

### PR DESCRIPTION
**Pull request by kakarot-dev**

### CODE REVIEW

**Comment by Deivu** [comment]
Rather than putting {?type}, just make it {type} [value], this marks it as docs as can be left as nullable or unfilled

**Comment by kakarot-dev** [comment]
> Rather than putting {?type}, just make it {type} [value], this marks it as docs as can be left as nullable or unfilled

So ill revert all the {?types} to {type} [value] ?

**Comment by kakarot-dev** [comment]
So is the above example correct? Or do you want it to be something else?
@Deivu

**Comment by Deivu** [comment]
@kakarot-dev You dont have to put an value on test, just putting `[]` around it is enough if the value is nullable

**Comment by kakarot-dev** [comment]
ok, will start working on it

**Comment by kakarot-dev** [comment]
@Deivu can you check if anything else is left?

**Comment by Deivu** [comment]
Shoukaku Connection 36, 46 and 51 should be marked as ? because those are nullable

**Comment by kakarot-dev** [comment]
Ok, doing that

**Comment by kakarot-dev** [comment]
Should be fixed now

anythig else u wanna fix?

**Review by Deivu — CHANGES_REQUESTED** [review]
Shoukaku Plauer L28 has missing ? as that is nullable as well

**Comment by Deivu** [comment]
https://github.com/Orchit07/Shoukaku/blob/89d3041729b53487fd8a5fcf91c18c0936808642/src/node/ShoukakuSocket.js#L181 Revert changes here, it was moved otherway round

**Comment by kakarot-dev** [comment]
> https://github.com/Orchit07/Shoukaku/blob/89d3041729b53487fd8a5fcf91c18c0936808642/src/node/ShoukakuSocket.js#L181
> 
> Revert changes here, it was moved otherway round

Shouldnt optional parameters be on the right hand side?

**Comment by Deivu** [comment]
both are optional there as far as I know, I just didn't put anything on reason so it defaults to undefined

**Comment by kakarot-dev** [comment]
Oh, i thought reason was needed, ill add a param too

**Comment by kakarot-dev** [comment]
Yea, done with that

**Comment by Deivu** [comment]
Double check the typings for the changes, there might be other changes like this one https://github.com/Orchit07/Shoukaku/blob/d2b4eb77f9add793007e948816a035dd17fd2c9e/types/node/ShoukakuSocket.d.ts#L37 that needs to be revert ed

**Comment by kakarot-dev** [comment]
Typings fixed , lemme check if they are more which are wrong

**Comment by Deivu** [comment]
seems fine

**Comment by kakarot-dev** [comment]
Ok then

**Comment by kakarot-dev** [comment]
Btw is the next branch ready for testing?

**Comment by Orchit07** [comment]
Thanks @kakarot-dev.

**Pull request merged**
